namespace BanksExchangeRates.Util
{
    public class CurrencyType
    {
        public Dictionary<string, string> currencyMapping1 = new Dictionary<string, string>
{
    { "USD", "US Dollar" },
    { "US DOLLAR", "US Dollar" },
    { "GBP", "Pound Sterling" },
    { "POUND STERLING", "Pound Sterling" },
    { "EUR", "Euro" },
    { "EURO", "Euro" },
    { "CHF", "Swiss Franc" },
    { "SWISS FRANK", "Swiss Franc" },
    { "SEK", "Swedish Kroner" },
    { "SWEDISH KRONER", "Swedish Kroner" },
    { "NOK", "Norwegian Kroner" },
    { "NORWEGIAN KRONER", "Norwegian Kroner" },
    { "DKK", "Danish Kroner" },
    { "DANISH KRONER", "Danish Kroner" },
    { "DJF", "Djibouti Franc" },
    { "DJIBOUTI FRANC", "Djibouti Franc" },
    { "JPY", "Japanese Yen" },
    { "JAPANIS YEN", "Japanese Yen" },
    { "CAD", "Canadian Dollar" },
    { "CANADIAN DOLLAR", "Canadian Dollar" },
    { "SAR", "Saudi Riyal" },
    { "SAUDI RIYAL", "Saudi Riyal" },
    { "AED", "UAE Dirham" },
    { "UAE DIRHAM", "UAE Dirham" },
    { "INR", "Indian Rupee" },
    { "INDIAN RUPEE", "Indian Rupee" },
    { "KES", "Kenyan Shilling" },
    { "KENNYAN SHILLING", "Kenyan Shilling" },
    { "AUD", "Australian Dollar" },
    { "AUSTRALIAN DOLLAR", "Australian Dollar" },
    { "ZAR", "South African Rand" },
    { "SOUTH AFRICAN RAND", "South African Rand" },
    { "CNY", "Chinese Yuan" },
    { "CHINESE YUAN", "Chinese Yuan" },
    { "KWD", "Kuwaiti Dinar" },
    { "KUWAITI DINAR", "Kuwaiti Dinar" },
    // Add more mappings as needed
};

        public Dictionary<string, string> currencyMapping = new Dictionary<string, string>
{
    { "USD", "US Dollar" },
    { "US DOLLAR", "US Dollar" },
    { "GBP", "Pound Sterling" },
    { "POUND STERLING", "Pound Sterling" },
    { "EUR", "Euro" },
    { "EURO", "Euro" },
    { "CHF", "Swiss Franc" },
    { "SWISS FRANK", "Swiss Franc" },
    { "SEK", "Swedish Kroner" },
    { "SWEDISH KRONER", "Swedish Kroner" },
    { "NOK", "Norwegian Kroner" },
    { "NORWEGIAN KRONER", "Norwegian Kroner" },
    { "DKK", "Danish Kroner" },
    { "DANISH KRONER", "Danish Kroner" },
    { "DJF", "Djibouti Franc" },
    { "DJIBOUTI FRANC", "Djibouti Franc" },
    { "JPY", "Japanese Yen" },
    { "JAPANIS YEN", "Japanese Yen" },
    { "CAD", "Canadian Dollar" },
    { "CANADIAN DOLLAR", "Canadian Dollar" },
    { "SAR", "Saudi Riyal" },
    { "SAUDI RIYAL", "Saudi Riyal" },
    { "AED", "UAE Dirham" },
    { "UAE DIRHAM", "UAE Dirham" },
    { "INR", "Indian Rupee" },
    { "INDIAN RUPEE", "Indian Rupee" },
    { "KES", "Kenyan Shilling" },
    { "KENNYAN SHILLING", "Kenyan Shilling" },
    { "AUD", "Australian Dollar" },
    { "AUSTRALIAN DOLLAR", "Australian Dollar" },
    { "ZAR", "South African Rand" },
    { "SOUTH AFRICAN RAND", "South African Rand" },
    { "CNY", "Chinese Yuan" },
    { "CHINESE YUAN", "Chinese Yuan" },
    { "KWD", "Kuwaiti Dinar" },
    { "KUWAITI DINAR", "Kuwaiti Dinar" },
    // Add more mappings as needed
};

    }
}
